---

- name: PROMETHEUS | Install
  import_tasks: install.yml
  tags:
    - install

- name: PROMETHEUS | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: PROMETHEUS | Service
  import_tasks: service.yml
  tags:
    - service
